version: '3.8'
services:
  customer-api:
    build:
      context: ./CustomerApi
      dockerfile: ./Dockerfile
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Customers;User=sa;Password=Your_password123;TrustServerCertificate=True;
      #- DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    depends_on:
      - sqlserver

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    user: root
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
